export const images = {
  yourlogo: "/assets/yourlogo.svg",
  brainwave: "/assets/brainwave.svg",
  check: "/assets/check.svg",
  check2: "/assets/check-02.svg",
  loading1: "/assets/loading-01.svg",
  brainwaveSymbol: "/assets/brainwave-symbol.svg",
  brainwaveWhiteSymbol: "/assets/brainwave-symbol-white.svg",
  play: "/assets/play.svg",
  gradient: "/assets/gradient.png",
  smallSphere: "/assets/4-small.png",
  grid: "/assets/grid.png",
  homeSmile: "/assets/home-smile.svg",
  file02: "/assets/file-02.svg",
  searchMd: "/assets/search-md.svg",
  plusSquare: "/assets/plus-square.svg",
  recording03: "/assets/recording-03.svg",
  recording01: "/assets/recording-01.svg",
  disc02: "/assets/disc-02.svg",
  chromecast: "/assets/chrome-cast.svg",
  sliders04: "/assets/sliders-04.svg",
  loading: "/assets/loading.png",
  background: "/assets/background.jpg",
  curve: "/assets/hero/curve.png",
  robot: "/assets/hero/robot.jpg",
  heroBackground: "/assets/hero/hero-background.jpg",
  curve1: "/assets/collaboration/curve-1.svg",
  curve2: "/assets/collaboration/curve-2.svg",
  discord: "/assets/collaboration/discord.png",
  figma: "/assets/collaboration/figma.png",
  framer: "/assets/collaboration/framer.png",
  notion: "/assets/collaboration/notion.png",
  photoshop: "/assets/collaboration/photoshop.png",
  protopie: "/assets/collaboration/protopie.png",
  raindrop: "/assets/collaboration/raindrop.png",
  slack: "/assets/collaboration/slack.png",
  service1: "/assets/services/service-1.png",
  service2: "/assets/services/service-2.png",
  service3: "/assets/services/service-3.png",
  lines: "/assets/pricing/lines.svg",
  stars: "/assets/pricing/stars.svg",
  coins: "/assets/roadmap/coins.png",
  done: "/assets/roadmap/done.svg",
  hero: "/assets/roadmap/hero.png",
  roadmap1: "/assets/roadmap/image-1.png",
  roadmap2: "/assets/roadmap/image-2.png",
  roadmap3: "/assets/roadmap/image-3.png",
  roadmap4: "/assets/roadmap/image-4.png",
  undone: "/assets/roadmap/undone.svg",
  notification1: "/assets/notification/image-1.png",
  notification2: "/assets/notification/image-2.png",
  notification3: "/assets/notification/image-3.png",
  notification4: "/assets/notification/image-4.png",
  benefitCard1: "/assets/benefits/card-1.svg",
  benefitCard2: "/assets/benefits/card-2.svg",
  benefitCard3: "/assets/benefits/card-3.svg",
  benefitCard4: "/assets/benefits/card-4.svg",
  benefitCard5: "/assets/benefits/card-5.svg",
  benefitCard6: "/assets/benefits/card-6.svg",
  benefitIcon1: "/assets/benefits/icon-1.svg",
  benefitIcon2: "/assets/benefits/icon-2.svg",
  benefitIcon3: "/assets/benefits/icon-3.svg",
  benefitIcon4: "/assets/benefits/icon-4.svg",
  benefitImage2: "/assets/benefits/image-2.png",
  discordBlack: "/assets/socials/discord.svg",
  facebook: "/assets/socials/facebook.svg",
  instagram: "/assets/socials/instagram.svg",
  telegram: "/assets/socials/telegram.svg",
  twitter: "/assets/socials/twitter.svg",
  quizicon: "/assets/circle/quizicon.png",
  flashcardsicon: "/assets/circle/flashcardsicon.png",
  summaryicon: "/assets/circle/summaryicon.png",
  pdficon: "/assets/circle/pdficon.png",
  youtubeicon: "/assets/circle/youtubeicon.png",
  fasticon: "/assets/circle/fasticon.png",
  gpaicon: "/assets/circle/gpaicon.png",
  voiceicon: "/assets/circle/voiceicon.png",
};

const {
  yourlogo,
  homeSmile,
  file02,
  searchMd,
  plusSquare,
  recording03,
  recording01,
  disc02,
  chromecast,
  sliders04,
  discord,
  figma,
  framer,
  notion,
  photoshop,
  protopie,
  raindrop,
  slack,
  roadmap1,
  roadmap2,
  roadmap3,
  roadmap4,
  notification2,
  notification3,
  notification4,
  benefitIcon1,
  benefitIcon2,
  benefitIcon3,
  benefitIcon4,
  benefitImage2,
  discordBlack,
  facebook,
  instagram,
  telegram,
  twitter,
  pdficon,
  youtubeicon,
  quizicon,
  flashcardsicon,
  summaryicon,
  fasticon,
  gpaicon,
  voiceicon,
} = images;

export const navigation = [
  {
    id: "0",
    title: "Features",
    url: "#features",
  },
  {
    id: "1",
    title: "Pricing",
    url: "#pricing",
  },
  {
    id: "2",
    title: "How to use",
    url: "#how-to-use",
  },
  {
    id: "3",
    title: "Roadmap",
    url: "#roadmap",
  },
  {
    id: "4",
    title: "New account",
    url: "#signup",
    onlyMobile: true,
  },
  {
    id: "5",
    title: "Sign in",
    url: "#login",
    onlyMobile: true,
  },
];

export const heroIcons = [homeSmile, file02, searchMd, plusSquare];

export const notificationImages = [notification4, notification3, notification2];

export const companyLogos = [yourlogo, yourlogo, yourlogo, yourlogo, yourlogo];

export const brainwaveServices = ["Photo generating", "Photo enhance", "Seamless Integration"];

export const brainwaveServicesIcons = [recording03, recording01, disc02, chromecast, sliders04];

export const roadmap = [
  {
    id: "0",
    title: "Voice Podcast Summary",
    text: "Transform your learning experience with AI-generated podcast summaries. Effortlessly listen and grasp the essence of any content in minutes.",
    date: "January 2025",
    status: "done",
    imageUrl: roadmap1,
    colorful: true,
  },
  {
    id: "1",
    title: "Gamification",
    text: "Motivate learners with gamified experiences. Earn badges and climb leaderboards by staying consistent and achieving milestones on the platform.",
    date: "May 2025",
    status: "progress",
    imageUrl: roadmap2,
  },
  {
    id: "2",
    title: "Analytics for Deep Insights",
    text: "Track your learning journey with detailed analytics. Understand your strengths, improve weak areas, and make data-driven progress every step of the way.",
    date: "May 2025",
    status: "progress",
    imageUrl: roadmap3,
  },
  {
    id: "3",
    title: "Collaborative Learning Tools",
    text: "Learn together, grow together. Collaborate with peers in real time to share notes, solve quizzes, and achieve learning goals as a team.",
    date: "July 2025",
    status: "progress",
    imageUrl: roadmap4,
  },
];

export const collabText =
  "Upload your files or links for instant AI summaries, quizzes, flashcards, and voice podcasts instantly.";

export const collabContent = [
  {
    id: "0",
    title: "Upload & Generate",
    text: collabText,
  },
  {
    id: "1",
    title: "Create & Customize",
  },
  {
    id: "2",
    title: "Learn & Master",
  },
];

export const collabApps = [
  {
    id: "0",
    title: "summaryicon",
    icon: summaryicon,
    width: 26,
    height: 36,
  },
  {
    id: "1",
    title: "quizicon",
    icon: quizicon,
    width: 34,
    height: 36,
  },
  {
    id: "2",
    title: "flashcardsicon",
    icon: flashcardsicon,
    width: 36,
    height: 28,
  },
  {
    id: "3",
    title: "voiceicon",
    icon: voiceicon,
    width: 34,
    height: 35,
  },
  {
    id: "4",
    title: "fasticon",
    icon: fasticon,
    width: 34,
    height: 34,
  },
  {
    id: "5",
    title: "gpaicon",
    icon: gpaicon,
    width: 34,
    height: 34,
  },
  {
    id: "6",
    title: "pdficon",
    icon: pdficon,
    width: 26,
    height: 34,
  },
  {
    id: "7",
    title: "youtubeicon",
    icon: youtubeicon,
    width: 38,
    height: 32,
  },
];

export const pricing = [
  {
    id: "0",
    title: "Monthly",
    description: "7.99 per month",
    price: "7.99",
    features: [
      "Access Anytime , Perfect for short-term projects or quick learning goals",
      "Create Unlimited Summaries📄, Flashcards🃏, and Quizzes📝 with ease",
      "No Strings Attached Cancel anytime, no commitments",
    ],
  },
  {
    id: "1",
    title: "3 Months",
    description: "Billed $17.99 Every 3 Months",
    price: "5.99",
    features: [
      "Save 25% when you commit to a full quarter",
      "Same features as Monthly Unlimited Summaries📄, Flashcards🃏, and Quizzes📝",
      "Great for learners with mid-term goals or preparing for exams",
    ],
  },
  {
    id: "2",
    title: "Yearly",
    description: "Billed $47.88 Annually",
    price: "3.99",
    features: [
      "Save 50% the ultimate value for long-term learners",
      "Full access to Unlimited Summaries📄, Flashcards🃏, and Quizzes📝 all year round",
      "Ideal for those committed to consistent learning and progress",
    ],
  },
];

export const benefits = [
  {
    id: "0",
    title: "Answers in a Snap!",
    text: "Have a tricky question? Just ask! Let AI uncover the answer for you faster than you can say ‘Google it’!",
    backgroundUrl: "assets/benefits/card-1.svg",
    iconUrl: benefitIcon1,
    imageUrl: benefitImage2,
  },
  {
    id: "1",
    title: "Be a Daily Genius",
    text: "Turn your daily grind into daily wins! With AcadoAi, every study session becomes a step toward brilliance.",
    backgroundUrl: "assets/benefits/card-2.svg",
    iconUrl: benefitIcon2,
    imageUrl: benefitImage2,
    light: true,
  },
  {
    id: "2",
    title: "Learn Anywhere, Anytime",
    text: "Whether you’re in the library, at home, or even in pajamas—AcadoAi is your always-ready learning buddy.",
    backgroundUrl: "assets/benefits/card-3.svg",
    iconUrl: benefitIcon3,
    imageUrl: benefitImage2,
  },
  {
    id: "3",
    title: "Speed Meets Smarts",
    text: "AI-powered insights so quick, it’s like having a supercomputer as your personal tutor!",
    backgroundUrl: "assets/benefits/card-4.svg",
    iconUrl: benefitIcon4,
    imageUrl: benefitImage2,
    light: true,
  },
  {
    id: "4",
    title: "Learning, Your Way",
    text: "Flashcards, quizzes, or summaries? You choose how you learn. AcadoAi adapts to your brain, not the other way around.",
    backgroundUrl: "assets/benefits/card-5.svg",
    iconUrl: benefitIcon1,
    imageUrl: benefitImage2,
  },
  {
    id: "5",
    title: "Unlock the Genius Within",
    text: "Your future self will thank you! Let AcadoAi supercharge your learning and make every moment count.",
    backgroundUrl: "assets/benefits/card-6.svg",
    iconUrl: benefitIcon2,
    imageUrl: benefitImage2,
  },
];

export const socials = [
  {
    id: "0",
    title: "Discord",
    iconUrl: discordBlack,
    url: "#",
  },
  {
    id: "1",
    title: "Twitter",
    iconUrl: twitter,
    url: "#",
  },
  {
    id: "2",
    title: "Instagram",
    iconUrl: instagram,
    url: "#",
  },
  {
    id: "3",
    title: "Telegram",
    iconUrl: telegram,
    url: "#",
  },
  {
    id: "4",
    title: "Facebook",
    iconUrl: facebook,
    url: "#",
  },
];
